// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'row.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Row _$RowFromJson(Map<String, dynamic> json) => Row(
      current: json['current'] as int?,
      rows: json['rows'] as int?,
      id: json['id'] as String?,
      createDate: json['createDate'] as String?,
      updateDate: json['updateDate'] as String?,
      createBy: json['createBy'] as String?,
      updateBy: json['updateBy'] as String?,
      delFlag: json['delFlag'] as bool?,
      name: json['name'] as String?,
      image: json['image'] as String?,
      productId: json['productId'] as String?,
      startTime: json['startTime'] as String?,
      endTime: json['endTime'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      number: json['number'] as int?,
      status: json['status'] as int?,
      shelfStatus: json['shelfStatus'] as bool?,
      isDisplay: json['isDisplay'] as int?,
      doorsill: json['doorsill'] as int?,
      doorsillRule: json['doorsillRule'],
      isRemain: json['isRemain'] as int?,
      reStartTime: json['reStartTime'],
      reEndTime: json['reEndTime'],
      reDoorsill: json['reDoorsill'],
      reDoorsillRule: json['reDoorsillRule'],
      reStatus: json['reStatus'] as int?,
      purchaseNumberMax: json['purchaseNumberMax'] as int?,
      singlePurchaseNumberMax: json['singlePurchaseNumberMax'] as int?,
      shelfFlag: json['shelfFlag'] as bool?,
      destroyStatus: json['destroyStatus'] as bool?,
      nftProductName: json['nftProductName'] as String?,
      productImage: json['productImage'] as String?,
      productCover: json['productCover'] as String?,
      productMintNumber: json['productMintNumber'] as int?,
      productPrice: (json['productPrice'] as num?)?.toDouble(),
      productCreatorId: json['productCreatorId'] as String?,
      productCreatorNickName: json['productCreatorNickName'] as String?,
      productCreatorAvatar: json['productCreatorAvatar'] as String?,
      productCreatorIntroduce: json['productCreatorIntroduce'],
      brandPartyName: json['brandPartyName'],
      brandPartyIntroduce: json['brandPartyIntroduce'],
      supervisorName: json['supervisorName'],
      supervisorIntroduce: json['supervisorIntroduce'],
      activityBuyNum: json['activityBuyNum'],
    );

Map<String, dynamic> _$RowToJson(Row instance) => <String, dynamic>{
      'current': instance.current,
      'rows': instance.rows,
      'id': instance.id,
      'createDate': instance.createDate,
      'updateDate': instance.updateDate,
      'createBy': instance.createBy,
      'updateBy': instance.updateBy,
      'delFlag': instance.delFlag,
      'name': instance.name,
      'image': instance.image,
      'productId': instance.productId,
      'startTime': instance.startTime,
      'endTime': instance.endTime,
      'price': instance.price,
      'number': instance.number,
      'status': instance.status,
      'shelfStatus': instance.shelfStatus,
      'isDisplay': instance.isDisplay,
      'doorsill': instance.doorsill,
      'doorsillRule': instance.doorsillRule,
      'isRemain': instance.isRemain,
      'reStartTime': instance.reStartTime,
      'reEndTime': instance.reEndTime,
      'reDoorsill': instance.reDoorsill,
      'reDoorsillRule': instance.reDoorsillRule,
      'reStatus': instance.reStatus,
      'purchaseNumberMax': instance.purchaseNumberMax,
      'singlePurchaseNumberMax': instance.singlePurchaseNumberMax,
      'shelfFlag': instance.shelfFlag,
      'destroyStatus': instance.destroyStatus,
      'nftProductName': instance.nftProductName,
      'productImage': instance.productImage,
      'productCover': instance.productCover,
      'productMintNumber': instance.productMintNumber,
      'productPrice': instance.productPrice,
      'productCreatorId': instance.productCreatorId,
      'productCreatorNickName': instance.productCreatorNickName,
      'productCreatorAvatar': instance.productCreatorAvatar,
      'productCreatorIntroduce': instance.productCreatorIntroduce,
      'brandPartyName': instance.brandPartyName,
      'brandPartyIntroduce': instance.brandPartyIntroduce,
      'supervisorName': instance.supervisorName,
      'supervisorIntroduce': instance.supervisorIntroduce,
      'activityBuyNum': instance.activityBuyNum,
    };
